### ISSUE TITLE
The Incidents in the Live of a Slave Girl - Design Cover

### ISSUE THREAD

**Issue by jjcastro** [citapress/books#7]

**Comment by jjcastro** [comment]
This is done.

**Comment by juliacastrov** [comment]
![Incidents-Thumnail](https://user-images.githubusercontent.com/25989958/56095471-6e08cd80-5eab-11e9-81f6-5f3595f0e4de.png)
![Incidents-Cover](https://user-images.githubusercontent.com/25989958/56095473-6f39fa80-5eab-11e9-89e3-aaf7cfe65de1.png)
